-- ============================================================
-- CampusOS - Smart Campus Management Platform
-- Database Schema (PostgreSQL 15+)
--
-- Apply order:
--   psql -d campusos -f db/schema.sql
--   psql -d campusos -f db/seed.sql
--
-- To rebuild from scratch (DESTRUCTIVE, dev only):
--   psql -d campusos -f db/reset.sql -f db/schema.sql -f db/seed.sql
--
-- Conventions
--   * All timestamps are TIMESTAMPTZ. The application stores UTC and
--     renders in Asia/Kolkata; never use naive TIMESTAMP here.
--   * Status columns are VARCHAR + CHECK rather than native ENUM so that
--     new states can be added without an ALTER TYPE migration.
--   * Every table that is mutated by users carries created_at/updated_at,
--     maintained by the set_updated_at() trigger.
-- ============================================================

-- ------------------------------------------------------------
-- Extensions
--   pgcrypto   -> gen_random_uuid() for certificate identifiers
--   btree_gist -> lets the bookings EXCLUDE constraint mix an equality
--                 test (venue_id) with a range overlap test (&&)
-- ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;


-- ------------------------------------------------------------
-- Shared trigger function: keeps updated_at honest
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 1. DEPARTMENTS
-- Referenced by users, venues and coordinator routing (FR12).
-- ============================================================

CREATE TABLE departments (
    department_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code       VARCHAR(16)  NOT NULL UNIQUE,
    dept_name       VARCHAR(120) NOT NULL UNIQUE,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_departments_updated_at
    BEFORE UPDATE ON departments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 2. ROLES  (FR3 - five hierarchical roles)
-- rank_level orders the hierarchy: lower number = higher authority,
-- so "can this user act on that user" is a single integer comparison.
-- ============================================================

CREATE TABLE roles (
    role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key    VARCHAR(32)  NOT NULL UNIQUE,
    role_name   VARCHAR(64)  NOT NULL UNIQUE,
    rank_level  SMALLINT     NOT NULL,

    CONSTRAINT chk_roles_key CHECK (role_key IN (
        'SUPER_ADMIN',
        'DEPT_COORDINATOR',
        'CLUB_HEAD',
        'CLUB_MEMBER',
        'STUDENT'
    ))
);


-- ============================================================
-- 3. USERS  (FR1, FR2, FR5)
-- password_hash is nullable because Gmail OAuth accounts have no
-- local password; chk_users_credential guarantees every row still has
-- exactly one usable way to authenticate.
-- ============================================================

CREATE TABLE users (
    user_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         VARCHAR(120) NOT NULL,
    email             VARCHAR(254) NOT NULL UNIQUE,
    password_hash     VARCHAR(255),
    oauth_provider    VARCHAR(32),
    oauth_subject     VARCHAR(255),
    phone             VARCHAR(20),
    department_id     INTEGER,
    academic_year     SMALLINT,
    profile_image_url TEXT,
    role_id           INTEGER      NOT NULL,
    is_verified       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at     TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles(role_id),

    CONSTRAINT fk_users_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id),

    -- A user authenticates by password, or by OAuth, or both - never neither.
    CONSTRAINT chk_users_credential CHECK (
        password_hash IS NOT NULL OR oauth_provider IS NOT NULL
    ),

    -- OAuth identity is all-or-nothing.
    CONSTRAINT chk_users_oauth_pair CHECK (
        (oauth_provider IS NULL AND oauth_subject IS NULL)
        OR (oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL)
    ),

    CONSTRAINT chk_users_academic_year CHECK (
        academic_year IS NULL OR academic_year BETWEEN 1 AND 5
    ),

    CONSTRAINT chk_users_email_shape CHECK (email = lower(email) AND email LIKE '%@%')
);

CREATE UNIQUE INDEX uq_users_oauth_identity
    ON users(oauth_provider, oauth_subject)
    WHERE oauth_provider IS NOT NULL;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 4. REFRESH TOKENS  (FR4 - session management)
-- Only the SHA-256 hash of the token is stored, so a database leak
-- does not hand an attacker usable sessions.
-- ============================================================

CREATE TABLE refresh_tokens (
    token_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER      NOT NULL,
    token_hash   VARCHAR(64)  NOT NULL UNIQUE,
    user_agent   VARCHAR(255),
    ip_address   INET,
    expires_at   TIMESTAMPTZ  NOT NULL,
    revoked_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


-- ============================================================
-- 5. OTPs
-- otp_code stores a hash, never the six plaintext digits.
-- ============================================================

CREATE TABLE otps (
    otp_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(254) NOT NULL,
    otp_hash     VARCHAR(64)  NOT NULL,
    purpose      VARCHAR(32)  NOT NULL DEFAULT 'EMAIL_VERIFICATION',
    attempts     SMALLINT     NOT NULL DEFAULT 0,
    expires_at   TIMESTAMPTZ  NOT NULL,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_otps_purpose CHECK (
        purpose IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET')
    ),
    CONSTRAINT chk_otps_attempts CHECK (attempts >= 0 AND attempts <= 10)
);


-- ============================================================
-- 6. SYSTEM SETTINGS  (FR9 - configurable buffer, and friends)
-- Single source of truth for values the SRS calls "configurable".
-- ============================================================

CREATE TABLE system_settings (
    setting_key    VARCHAR(64) PRIMARY KEY,
    setting_value  TEXT        NOT NULL,
    description    TEXT,
    updated_by     INTEGER,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_system_settings_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);


-- ============================================================
-- 7. VENUES  (FR6 - building / floor / capacity / equipment search)
-- buffer_minutes is a per-venue override; NULL means "inherit the
-- venue.default_buffer_minutes system setting".
-- ============================================================

CREATE TABLE venues (
    venue_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name      VARCHAR(120) NOT NULL,
    building        VARCHAR(80)  NOT NULL,
    floor           SMALLINT     NOT NULL,
    department_id   INTEGER,
    venue_type      VARCHAR(32)  NOT NULL,
    capacity        INTEGER      NOT NULL,
    location        VARCHAR(160),
    equipment       TEXT[]       NOT NULL DEFAULT '{}',
    buffer_minutes  SMALLINT,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_venues_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id),

    CONSTRAINT uq_venues_name_building UNIQUE (building, venue_name),

    CONSTRAINT chk_venues_type CHECK (venue_type IN (
        'CLASSROOM', 'LABORATORY', 'SEMINAR_HALL', 'AUDITORIUM',
        'CONFERENCE_ROOM', 'SPORTS_GROUND', 'OPEN_AIR'
    )),

    CONSTRAINT chk_venues_capacity CHECK (capacity > 0),
    CONSTRAINT chk_venues_floor CHECK (floor >= 0),
    CONSTRAINT chk_venues_buffer CHECK (
        buffer_minutes IS NULL OR (buffer_minutes >= 0 AND buffer_minutes <= 120)
    )
);

CREATE TRIGGER trg_venues_updated_at
    BEFORE UPDATE ON venues
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 8. CLUBS  (FR11)
-- ============================================================

CREATE TABLE clubs (
    club_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_name       VARCHAR(120) NOT NULL UNIQUE,
    description     TEXT,
    department_id   INTEGER,
    club_head_id    INTEGER,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_clubs_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id),

    CONSTRAINT fk_clubs_club_head
        FOREIGN KEY (club_head_id) REFERENCES users(user_id)
);

CREATE TRIGGER trg_clubs_updated_at
    BEFORE UPDATE ON clubs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 9. CLUB MEMBERS  (FR11 - "manage organizing team members")
-- ============================================================

CREATE TABLE club_members (
    club_member_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id         INTEGER     NOT NULL,
    user_id         INTEGER     NOT NULL,
    position        VARCHAR(64) NOT NULL DEFAULT 'MEMBER',
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_club_members_club
        FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE CASCADE,

    CONSTRAINT fk_club_members_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT uq_club_members UNIQUE (club_id, user_id)
);


-- ============================================================
-- 10. EVENTS  (FR14 category filtering, FR17 recommendations)
-- booked_seats is a denormalised counter maintained inside the same
-- transaction as event_registrations; chk_events_booked_within_capacity
-- is the hard backstop against overbooking (FR15).
-- ============================================================

CREATE TABLE events (
    event_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id          INTEGER      NOT NULL,
    created_by       INTEGER      NOT NULL,
    title            VARCHAR(200) NOT NULL,
    description      TEXT,
    category         VARCHAR(32)  NOT NULL,
    event_scope      VARCHAR(16)  NOT NULL DEFAULT 'CLUB',
    event_date       DATE         NOT NULL,
    start_time       TIME         NOT NULL,
    end_time         TIME         NOT NULL,
    status           VARCHAR(24)  NOT NULL DEFAULT 'DRAFT',
    max_seats        INTEGER,
    booked_seats     INTEGER      NOT NULL DEFAULT 0,
    eligible_departments INTEGER[] NOT NULL DEFAULT '{}',  -- empty = open to all
    eligible_years   SMALLINT[]   NOT NULL DEFAULT '{}',   -- empty = open to all
    banner_url       TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_events_club
        FOREIGN KEY (club_id) REFERENCES clubs(club_id),

    CONSTRAINT fk_events_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),

    CONSTRAINT chk_events_category CHECK (category IN (
        'TECHNICAL', 'CULTURAL', 'SPORTS', 'WORKSHOP',
        'SEMINAR', 'PLACEMENT', 'SOCIAL', 'OTHER'
    )),

    CONSTRAINT chk_events_scope CHECK (event_scope IN ('CLUB', 'DEPARTMENT', 'COLLEGE')),

    CONSTRAINT chk_events_status CHECK (status IN (
        'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED',
        'REJECTED', 'CANCELLED', 'COMPLETED'
    )),

    CONSTRAINT chk_events_time CHECK (end_time > start_time),
    CONSTRAINT chk_events_max_seats CHECK (max_seats IS NULL OR max_seats > 0),
    CONSTRAINT chk_events_booked_seats CHECK (booked_seats >= 0),

    CONSTRAINT chk_events_booked_within_capacity CHECK (
        max_seats IS NULL OR booked_seats <= max_seats
    )
);

CREATE TRIGGER trg_events_updated_at
    BEFORE UPDATE ON events
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 11. BOOKINGS  (FR7-FR13)
--
-- start_at / end_at are the authoritative venue reservation window and
-- are the ONLY columns the conflict engine reads. They are derived by
-- the application from the event schedule at request time; events keeps
-- event_date/start_time/end_time for display and reporting.
--
-- The EXCLUDE constraint is the last line of defence: even if the
-- application-level SELECT ... FOR UPDATE logic (FR10) were buggy,
-- PostgreSQL itself refuses two overlapping APPROVED bookings on one
-- venue. The configurable setup/teardown buffer (FR9) is applied by the
-- application query, which is why the constraint uses the raw window.
-- ============================================================

CREATE TABLE bookings (
    booking_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id            INTEGER      NOT NULL,
    venue_id            INTEGER      NOT NULL,
    requested_by        INTEGER      NOT NULL,
    approved_by         INTEGER,
    start_at            TIMESTAMPTZ  NOT NULL,
    end_at              TIMESTAMPTZ  NOT NULL,
    extension_minutes   SMALLINT     NOT NULL DEFAULT 0,
    status              VARCHAR(24)  NOT NULL DEFAULT 'PENDING',
    rejection_reason    TEXT,
    decided_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bookings_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_bookings_venue
        FOREIGN KEY (venue_id) REFERENCES venues(venue_id),

    CONSTRAINT fk_bookings_requested_by
        FOREIGN KEY (requested_by) REFERENCES users(user_id),

    CONSTRAINT fk_bookings_approved_by
        FOREIGN KEY (approved_by) REFERENCES users(user_id),

    CONSTRAINT chk_bookings_status CHECK (status IN (
        'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'MODIFICATION_REQUESTED'
    )),

    CONSTRAINT chk_bookings_window CHECK (end_at > start_at),

    CONSTRAINT chk_bookings_extension CHECK (
        extension_minutes >= 0 AND extension_minutes <= 15
    ),

    -- FR13: a rejection must carry a recorded reason.
    CONSTRAINT chk_bookings_rejection_reason CHECK (
        status <> 'REJECTED' OR (rejection_reason IS NOT NULL AND length(btrim(rejection_reason)) > 0)
    ),

    -- Any decided booking records who decided it and when.
    CONSTRAINT chk_bookings_decision_audit CHECK (
        status IN ('PENDING', 'CANCELLED')
        OR (approved_by IS NOT NULL AND decided_at IS NOT NULL)
    ),

    -- FR10: zero duplicate venue bookings, enforced by the database.
    CONSTRAINT excl_bookings_no_overlap
        EXCLUDE USING gist (
            venue_id WITH =,
            tstzrange(start_at, end_at, '[)') WITH &&
        ) WHERE (status = 'APPROVED')
);

CREATE TRIGGER trg_bookings_updated_at
    BEFORE UPDATE ON bookings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 12. EVENT REGISTRATIONS / RSVP  (FR15, FR16)
-- Distinct from attendance: this is the seat reservation, attendance is
-- what happened on the day.
-- ============================================================

CREATE TABLE event_registrations (
    registration_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         INTEGER     NOT NULL,
    student_id       INTEGER     NOT NULL,
    status           VARCHAR(16) NOT NULL DEFAULT 'RESERVED',
    seats            SMALLINT    NOT NULL DEFAULT 1,
    registered_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at     TIMESTAMPTZ,

    CONSTRAINT fk_event_registrations_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_event_registrations_student
        FOREIGN KEY (student_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT uq_event_registrations UNIQUE (event_id, student_id),

    CONSTRAINT chk_event_registrations_status CHECK (
        status IN ('RESERVED', 'CANCELLED', 'WAITLISTED')
    ),

    CONSTRAINT chk_event_registrations_seats CHECK (seats > 0),

    CONSTRAINT chk_event_registrations_cancel CHECK (
        (status = 'CANCELLED') = (cancelled_at IS NOT NULL)
    )
);


-- ============================================================
-- 13. ATTENDANCE
-- ============================================================

CREATE TABLE attendance (
    attendance_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INTEGER     NOT NULL,
    student_id      INTEGER     NOT NULL,
    status          VARCHAR(16) NOT NULL,
    marked_by       INTEGER,
    marked_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_attendance_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_attendance_student
        FOREIGN KEY (student_id) REFERENCES users(user_id),

    CONSTRAINT fk_attendance_marked_by
        FOREIGN KEY (marked_by) REFERENCES users(user_id),

    CONSTRAINT uq_attendance_event_student UNIQUE (event_id, student_id),

    CONSTRAINT chk_attendance_status CHECK (status IN ('PRESENT', 'ABSENT', 'EXCUSED'))
);


-- ============================================================
-- 14. CERTIFICATES
-- NOTE: certificates and event_materials are implemented here but are
-- not described in the SRS. Either add them to SRS section 10 or drop
-- these two tables before the final review.
-- ============================================================

CREATE TABLE certificates (
    certificate_uuid    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id            INTEGER     NOT NULL,
    student_id          INTEGER     NOT NULL,
    certificate_type    VARCHAR(32) NOT NULL,
    issued_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_certificates_event
        FOREIGN KEY (event_id) REFERENCES events(event_id),

    CONSTRAINT fk_certificates_student
        FOREIGN KEY (student_id) REFERENCES users(user_id),

    CONSTRAINT uq_certificate_event_student_type
        UNIQUE (event_id, student_id, certificate_type),

    CONSTRAINT chk_certificates_type CHECK (
        certificate_type IN ('PARTICIPATION', 'WINNER', 'ORGANIZER', 'VOLUNTEER')
    )
);


-- ============================================================
-- 15. EVENT MATERIALS
-- ============================================================

CREATE TABLE event_materials (
    material_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INTEGER      NOT NULL,
    title           VARCHAR(200) NOT NULL,
    file_url        TEXT         NOT NULL,
    file_type       VARCHAR(32),
    uploaded_by     INTEGER,
    uploaded_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_event_materials_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_event_materials_uploaded_by
        FOREIGN KEY (uploaded_by) REFERENCES users(user_id)
);


-- ============================================================
-- 16. NOTIFICATIONS  (FR19)
-- ============================================================

CREATE TABLE notifications (
    notification_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            INTEGER      NOT NULL,
    event_id           INTEGER,
    booking_id         INTEGER,
    category           VARCHAR(32)  NOT NULL DEFAULT 'GENERAL',
    title              VARCHAR(200) NOT NULL,
    message            TEXT         NOT NULL,
    is_read            BOOLEAN      NOT NULL DEFAULT FALSE,
    read_at            TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT fk_notifications_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_notifications_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,

    CONSTRAINT chk_notifications_category CHECK (category IN (
        'GENERAL', 'EVENT_PUBLISHED', 'EVENT_REMINDER', 'EVENT_CANCELLED',
        'BOOKING_APPROVED', 'BOOKING_REJECTED', 'REGISTRATION_CONFIRMED', 'ANNOUNCEMENT'
    ))
);


-- ============================================================
-- 17. EVENT REMINDERS  (FR19 - the 2-day / 2-hour scheduled workers)
-- The UNIQUE constraint is what makes the worker idempotent: a restart
-- or an overlapping tick cannot send the same reminder twice.
-- ============================================================

CREATE TABLE event_reminders (
    reminder_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INTEGER     NOT NULL,
    reminder_type   VARCHAR(16) NOT NULL,
    scheduled_for   TIMESTAMPTZ NOT NULL,
    dispatched_at   TIMESTAMPTZ,
    recipient_count INTEGER,

    CONSTRAINT fk_event_reminders_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT uq_event_reminders UNIQUE (event_id, reminder_type),

    CONSTRAINT chk_event_reminders_type CHECK (reminder_type IN ('T_MINUS_2D', 'T_MINUS_2H'))
);


-- ============================================================
-- 18. ADMIN LOGS  (FR20 - immutable audit trail)
-- ============================================================

CREATE TABLE admin_logs (
    log_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id        INTEGER      NOT NULL,
    booking_id      INTEGER,
    action          VARCHAR(64)  NOT NULL,
    target_type     VARCHAR(32),
    target_id       INTEGER,
    details         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    ip_address      INET,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_admin_logs_admin
        FOREIGN KEY (admin_id) REFERENCES users(user_id),

    CONSTRAINT fk_admin_logs_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE SET NULL
);

-- FR20 says the audit trail is immutable. Enforce it in the database so
-- that no application bug - and no ad-hoc psql session - can rewrite history.
CREATE OR REPLACE FUNCTION reject_admin_log_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'admin_logs is append-only (attempted %)', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_admin_logs_immutable
    BEFORE UPDATE OR DELETE ON admin_logs
    FOR EACH ROW EXECUTE FUNCTION reject_admin_log_mutation();


-- ============================================================
-- INDEXES
-- Only indexes backing a query the application actually issues.
-- ============================================================

CREATE INDEX idx_users_role_id             ON users(role_id);
CREATE INDEX idx_users_department_id       ON users(department_id);

CREATE INDEX idx_refresh_tokens_user_id    ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

CREATE INDEX idx_otps_email_purpose        ON otps(email, purpose);

CREATE INDEX idx_venues_building_floor     ON venues(building, floor);
CREATE INDEX idx_venues_department_id      ON venues(department_id);
CREATE INDEX idx_venues_capacity           ON venues(capacity);

CREATE INDEX idx_clubs_club_head_id        ON clubs(club_head_id);
CREATE INDEX idx_clubs_department_id       ON clubs(department_id);

CREATE INDEX idx_club_members_user_id      ON club_members(user_id);

CREATE INDEX idx_events_club_id            ON events(club_id);
CREATE INDEX idx_events_created_by         ON events(created_by);
CREATE INDEX idx_events_event_date         ON events(event_date);
CREATE INDEX idx_events_status             ON events(status);
CREATE INDEX idx_events_category           ON events(category);
-- Backs the student discovery feed (FR14): published events, soonest first.
CREATE INDEX idx_events_feed               ON events(event_date, start_time)
    WHERE status = 'PUBLISHED';

CREATE INDEX idx_bookings_event_id         ON bookings(event_id);
CREATE INDEX idx_bookings_requested_by     ON bookings(requested_by);
CREATE INDEX idx_bookings_approved_by      ON bookings(approved_by);
CREATE INDEX idx_bookings_status           ON bookings(status);
-- Backs the conflict-detection scan (FR8) and the calendar view.
CREATE INDEX idx_bookings_venue_window     ON bookings(venue_id, start_at, end_at);
-- Backs the coordinator approval inbox (FR13).
CREATE INDEX idx_bookings_pending_inbox    ON bookings(venue_id, start_at)
    WHERE status = 'PENDING';

CREATE INDEX idx_event_registrations_event_id   ON event_registrations(event_id);
CREATE INDEX idx_event_registrations_student_id ON event_registrations(student_id);

CREATE INDEX idx_attendance_event_id       ON attendance(event_id);
CREATE INDEX idx_attendance_student_id     ON attendance(student_id);

CREATE INDEX idx_certificates_event_id     ON certificates(event_id);
CREATE INDEX idx_certificates_student_id   ON certificates(student_id);

CREATE INDEX idx_event_materials_event_id  ON event_materials(event_id);

CREATE INDEX idx_notifications_event_id    ON notifications(event_id);
-- Backs the notification bell: this user's unread items, newest first.
CREATE INDEX idx_notifications_user_unread ON notifications(user_id, created_at DESC)
    WHERE is_read = FALSE;

-- Backs the reminder worker's "what is due now" sweep.
CREATE INDEX idx_event_reminders_due       ON event_reminders(scheduled_for)
    WHERE dispatched_at IS NULL;

CREATE INDEX idx_admin_logs_admin_id       ON admin_logs(admin_id);
CREATE INDEX idx_admin_logs_booking_id     ON admin_logs(booking_id);
CREATE INDEX idx_admin_logs_created_at     ON admin_logs(created_at DESC);
