-- ============================================================
-- CampusOS - Smart Campus Management Platform
-- Database Schema
-- PostgreSQL 18.x
-- ============================================================

-- ============================================================
-- Optional extension
-- Used for generating UUID values for certificates.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ============================================================
-- 1. ROLES
-- ============================================================

CREATE TABLE roles (
    role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR NOT NULL UNIQUE
);


-- ============================================================
-- 2. USERS
-- ============================================================

CREATE TABLE users (
    user_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR NOT NULL,
    email           VARCHAR NOT NULL UNIQUE,
    password_hash   VARCHAR NOT NULL,
    department      VARCHAR,
    role_id         INTEGER NOT NULL,
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id)
);


-- ============================================================
-- 3. OTPs
-- ============================================================

CREATE TABLE otps (
    otp_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR NOT NULL,
    otp_code        VARCHAR(6) NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 4. VENUES
-- ============================================================

CREATE TABLE venues (
    venue_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name      VARCHAR NOT NULL,
    building        VARCHAR,
    floor           INTEGER,
    department      VARCHAR,
    venue_type      VARCHAR,
    capacity        INTEGER,
    location        VARCHAR,

    CONSTRAINT chk_venue_capacity
        CHECK (capacity IS NULL OR capacity >= 0)
);


-- ============================================================
-- 5. CLUBS
-- ============================================================

CREATE TABLE clubs (
    club_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_name       VARCHAR NOT NULL UNIQUE,
    description     TEXT,
    club_head_id    INTEGER,

    CONSTRAINT fk_clubs_club_head
        FOREIGN KEY (club_head_id)
        REFERENCES users(user_id)
);


-- ============================================================
-- 6. EVENTS
-- ============================================================

CREATE TABLE events (
    event_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id         INTEGER NOT NULL,
    created_by      INTEGER NOT NULL,
    title           VARCHAR NOT NULL,
    description     TEXT,
    event_date      DATE NOT NULL,
    start_time      TIME NOT NULL,
    end_time        TIME NOT NULL,
    status          VARCHAR NOT NULL,
    max_seats       INTEGER,
    booked_seats    INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_events_club
        FOREIGN KEY (club_id)
        REFERENCES clubs(club_id),

    CONSTRAINT fk_events_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

    CONSTRAINT chk_events_time
        CHECK (end_time > start_time),

    CONSTRAINT chk_events_max_seats
        CHECK (max_seats IS NULL OR max_seats >= 0),

    CONSTRAINT chk_events_booked_seats
        CHECK (booked_seats >= 0),

    CONSTRAINT chk_events_booked_within_capacity
        CHECK (
            max_seats IS NULL
            OR booked_seats <= max_seats
        )
);


-- ============================================================
-- 7. ATTENDANCE
-- ============================================================

CREATE TABLE attendance (
    attendance_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INTEGER NOT NULL,
    student_id      INTEGER NOT NULL,
    status          VARCHAR NOT NULL,

    CONSTRAINT fk_attendance_event
        FOREIGN KEY (event_id)
        REFERENCES events(event_id),

    CONSTRAINT fk_attendance_student
        FOREIGN KEY (student_id)
        REFERENCES users(user_id),

    CONSTRAINT uq_attendance_event_student
        UNIQUE (event_id, student_id)
);


-- ============================================================
-- 8. CERTIFICATES
-- ============================================================

CREATE TABLE certificates (
    certificate_uuid    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id            INTEGER NOT NULL,
    student_id          INTEGER NOT NULL,
    certificate_type    VARCHAR NOT NULL,
    issued_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_certificates_event
        FOREIGN KEY (event_id)
        REFERENCES events(event_id),

    CONSTRAINT fk_certificates_student
        FOREIGN KEY (student_id)
        REFERENCES users(user_id),

    CONSTRAINT uq_certificate_event_student_type
        UNIQUE (event_id, student_id, certificate_type)
);


-- ============================================================
-- 9. EVENT MATERIALS
-- ============================================================

CREATE TABLE event_materials (
    material_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INTEGER NOT NULL,
    title           VARCHAR NOT NULL,
    file_url        TEXT NOT NULL,
    file_type       VARCHAR,
    uploaded_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_event_materials_event
        FOREIGN KEY (event_id)
        REFERENCES events(event_id)
);


-- ============================================================
-- 10. BOOKINGS
-- ============================================================

CREATE TABLE bookings (
    booking_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id            INTEGER NOT NULL,
    venue_id            INTEGER NOT NULL,
    requested_by        INTEGER NOT NULL,
    approved_by         INTEGER,
    booking_date        TIMESTAMP NOT NULL,
    extension_minutes   INTEGER NOT NULL DEFAULT 0,
    status              VARCHAR NOT NULL,

    CONSTRAINT fk_bookings_event
        FOREIGN KEY (event_id)
        REFERENCES events(event_id),

    CONSTRAINT fk_bookings_venue
        FOREIGN KEY (venue_id)
        REFERENCES venues(venue_id),

    CONSTRAINT fk_bookings_requested_by
        FOREIGN KEY (requested_by)
        REFERENCES users(user_id),

    CONSTRAINT fk_bookings_approved_by
        FOREIGN KEY (approved_by)
        REFERENCES users(user_id),

    CONSTRAINT chk_bookings_extension_minutes
        CHECK (
            extension_minutes >= 0
            AND extension_minutes <= 15
        )
);


-- ============================================================
-- 11. NOTIFICATIONS
-- ============================================================

CREATE TABLE notifications (
    notification_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            INTEGER NOT NULL,
    event_id           INTEGER,
    title              VARCHAR NOT NULL,
    message            TEXT NOT NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_notifications_event
        FOREIGN KEY (event_id)
        REFERENCES events(event_id)
);


-- ============================================================
-- 12. ADMIN LOGS
-- ============================================================

CREATE TABLE admin_logs (
    log_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id        INTEGER NOT NULL,
    booking_id      INTEGER,
    action          VARCHAR NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_admin_logs_admin
        FOREIGN KEY (admin_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_admin_logs_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id)
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_users_role_id
    ON users(role_id);

CREATE INDEX idx_users_department
    ON users(department);

CREATE INDEX idx_otps_email
    ON otps(email);

CREATE INDEX idx_clubs_club_head_id
    ON clubs(club_head_id);

CREATE INDEX idx_events_club_id
    ON events(club_id);

CREATE INDEX idx_events_created_by
    ON events(created_by);

CREATE INDEX idx_events_event_date
    ON events(event_date);

CREATE INDEX idx_events_status
    ON events(status);

CREATE INDEX idx_attendance_event_id
    ON attendance(event_id);

CREATE INDEX idx_attendance_student_id
    ON attendance(student_id);

CREATE INDEX idx_certificates_event_id
    ON certificates(event_id);

CREATE INDEX idx_certificates_student_id
    ON certificates(student_id);

CREATE INDEX idx_event_materials_event_id
    ON event_materials(event_id);

CREATE INDEX idx_bookings_event_id
    ON bookings(event_id);

CREATE INDEX idx_bookings_venue_id
    ON bookings(venue_id);

CREATE INDEX idx_bookings_requested_by
    ON bookings(requested_by);

CREATE INDEX idx_bookings_approved_by
    ON bookings(approved_by);

CREATE INDEX idx_bookings_booking_date
    ON bookings(booking_date);

CREATE INDEX idx_notifications_user_id
    ON notifications(user_id);

CREATE INDEX idx_notifications_event_id
    ON notifications(event_id);

CREATE INDEX idx_admin_logs_admin_id
    ON admin_logs(admin_id);

CREATE INDEX idx_admin_logs_booking_id
    ON admin_logs(booking_id);
