-- ============================================================
-- CampusOS - Smart Campus Management Platform
-- Database Schema (PostgreSQL 15+)
--
-- Apply order:
--   psql -d campusos -f db/schema.sql
--   psql -d campusos -f db/seed.sql
--
-- To rebuild from scratch (DESTRUCTIVE, dev only):
--   psql -d campusos -f db/reset.sql -f db/schema.sql -f db/seed.sql
--
-- Conventions
--   * All timestamps are TIMESTAMPTZ. The application stores UTC and
--     renders in Asia/Kolkata; never use naive TIMESTAMP here.
--   * Status columns are VARCHAR + CHECK rather than native ENUM so that
--     new states can be added without an ALTER TYPE migration.
--   * Every table that is mutated by users carries created_at/updated_at,
--     maintained by the set_updated_at() trigger.
-- ============================================================

-- ------------------------------------------------------------
-- Extensions
--   pgcrypto   -> gen_random_uuid() for certificate identifiers
--   btree_gist -> lets the bookings EXCLUDE constraint mix an equality
--                 test (venue_id) with a range overlap test (&&)
-- ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;


-- ------------------------------------------------------------
-- Shared trigger function: keeps updated_at honest
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 1. DEPARTMENTS
-- Referenced by users, venues and coordinator routing (FR12).
-- ============================================================

CREATE TABLE departments (
    department_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code       VARCHAR(16)  NOT NULL UNIQUE,
    dept_name       VARCHAR(120) NOT NULL UNIQUE,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_departments_updated_at
    BEFORE UPDATE ON departments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 2. ROLES  (FR3 - five hierarchical roles)
-- rank_level orders the hierarchy: lower number = higher authority,
-- so "can this user act on that user" is a single integer comparison.
-- ============================================================

CREATE TABLE roles (
    role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key    VARCHAR(32)  NOT NULL UNIQUE,
    role_name   VARCHAR(64)  NOT NULL UNIQUE,
    rank_level  SMALLINT     NOT NULL,

    CONSTRAINT chk_roles_key CHECK (role_key IN (
        'SUPER_ADMIN',
        'DEPT_COORDINATOR',
        'CLUB_HEAD',
        'CLUB_MEMBER',
        'STUDENT'
    ))
);


-- ============================================================
-- 3. USERS  (FR1, FR2, FR5)
-- password_hash is nullable because Gmail OAuth accounts have no
-- local password; chk_users_credential guarantees every row still has
-- exactly one usable way to authenticate.
-- ============================================================

CREATE TABLE users (
    user_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         VARCHAR(120) NOT NULL,
    email             VARCHAR(254) NOT NULL UNIQUE,
    password_hash     VARCHAR(255),
    oauth_provider    VARCHAR(32),
    oauth_subject     VARCHAR(255),
    phone             VARCHAR(20),
    department_id     INTEGER,
    academic_year     SMALLINT,
    profile_image_url TEXT,
    role_id           INTEGER      NOT NULL,
    is_verified       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at     TIMESTAMPTZ,
    -- Brute-force lockout (NFR: login protection). Reset on success.
    failed_login_attempts SMALLINT NOT NULL DEFAULT 0,
    locked_until      TIMESTAMPTZ,
    -- Shown on the security page. Ending old sessions on a change is done by
    -- revoking refresh_tokens, which access tokens are checked against.
    password_changed_at TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles(role_id),

    CONSTRAINT fk_users_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id),

    -- A user authenticates by password, or by OAuth, or both - never neither.
    CONSTRAINT chk_users_credential CHECK (
        password_hash IS NOT NULL OR oauth_provider IS NOT NULL
    ),

    -- OAuth identity is all-or-nothing.
    CONSTRAINT chk_users_oauth_pair CHECK (
        (oauth_provider IS NULL AND oauth_subject IS NULL)
        OR (oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL)
    ),

    CONSTRAINT chk_users_academic_year CHECK (
        academic_year IS NULL OR academic_year BETWEEN 1 AND 5
    ),

    CONSTRAINT chk_users_email_shape CHECK (email = lower(email) AND email LIKE '%@%'),

    CONSTRAINT chk_users_failed_logins CHECK (failed_login_attempts >= 0)
);

CREATE UNIQUE INDEX uq_users_oauth_identity
    ON users(oauth_provider, oauth_subject)
    WHERE oauth_provider IS NOT NULL;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 4. REFRESH TOKENS  (FR4 - session management)
-- Only the SHA-256 hash of the token is stored, so a database leak
-- does not hand an attacker usable sessions.
--
-- Tokens rotate on every refresh. All tokens descended from one sign-in
-- share a family_id; presenting an already-rotated token means it was
-- stolen and replayed, so the whole family is revoked.
-- ============================================================

CREATE TABLE refresh_tokens (
    token_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER      NOT NULL,
    family_id    UUID         NOT NULL,
    token_hash   VARCHAR(64)  NOT NULL UNIQUE,
    user_agent   VARCHAR(255),
    ip_address   INET,
    expires_at   TIMESTAMPTZ  NOT NULL,
    revoked_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


-- ============================================================
-- 5. OTPs
-- otp_hash stores an HMAC-SHA256 keyed with a server secret, never the
-- six plaintext digits: a plain hash of a 6-digit code is reversible in
-- a millisecond by trying all one million values.
-- ============================================================

CREATE TABLE otps (
    otp_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(254) NOT NULL,
    otp_hash     VARCHAR(64)  NOT NULL,
    purpose      VARCHAR(32)  NOT NULL DEFAULT 'EMAIL_VERIFICATION',
    attempts     SMALLINT     NOT NULL DEFAULT 0,
    expires_at   TIMESTAMPTZ  NOT NULL,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_otps_purpose CHECK (
        purpose IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET')
    ),
    CONSTRAINT chk_otps_attempts CHECK (attempts >= 0 AND attempts <= 10)
);


-- ============================================================
-- 6. SYSTEM SETTINGS  (FR9 - configurable buffer, and friends)
-- Single source of truth for values the SRS calls "configurable".
-- ============================================================

CREATE TABLE system_settings (
    setting_key    VARCHAR(64) PRIMARY KEY,
    setting_value  TEXT        NOT NULL,
    description    TEXT,
    updated_by     INTEGER,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_system_settings_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);


-- ============================================================
-- 7. VENUES  (FR6 - building / floor / capacity / equipment search)
-- buffer_minutes is a per-venue override; NULL means "inherit the
-- venue.default_buffer_minutes system setting".
-- ============================================================

CREATE TABLE venues (
    venue_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name      VARCHAR(120) NOT NULL,
    building        VARCHAR(80)  NOT NULL,
    floor           SMALLINT     NOT NULL,
    department_id   INTEGER,
    venue_type      VARCHAR(32)  NOT NULL,
    capacity        INTEGER      NOT NULL,
    location        VARCHAR(160),
    buffer_minutes  SMALLINT,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_venues_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id),

    CONSTRAINT uq_venues_name_building UNIQUE (building, venue_name),

    CONSTRAINT chk_venues_type CHECK (venue_type IN (
        'CLASSROOM', 'LABORATORY', 'SEMINAR_HALL', 'AUDITORIUM',
        'CONFERENCE_ROOM', 'SPORTS_GROUND', 'OPEN_AIR'
    )),

    CONSTRAINT chk_venues_capacity CHECK (capacity > 0),
    CONSTRAINT chk_venues_floor CHECK (floor >= 0),
    CONSTRAINT chk_venues_buffer CHECK (
        buffer_minutes IS NULL OR (buffer_minutes >= 0 AND buffer_minutes <= 120)
    )
);

CREATE TRIGGER trg_venues_updated_at
    BEFORE UPDATE ON venues
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ------------------------------------------------------------
-- 7a. EQUIPMENT (lookup table) and VENUE_EQUIPMENT (junction table)
--
-- venues.equipment used to be a TEXT[] column - a repeating group, which
-- breaks 1NF (DBMS Unit 3): "PROJECTOR" and "AC" were values, not rows, so
-- they could not be referenced, constrained or reported on individually.
-- This is also the project's composite-primary-key example (DBMS Unit 3,
-- "keys"): venue_equipment has no surrogate id at all - the pair
-- (venue_id, equipment_id) IS the identity of the fact "this venue has
-- this equipment", so it is the primary key.
-- ------------------------------------------------------------

CREATE TABLE equipment (
    equipment_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_code  VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE venue_equipment (
    venue_id        INTEGER NOT NULL,
    equipment_id    INTEGER NOT NULL,

    PRIMARY KEY (venue_id, equipment_id),

    CONSTRAINT fk_venue_equipment_venue
        FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,

    CONSTRAINT fk_venue_equipment_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id) ON DELETE CASCADE
);


-- ============================================================
-- 8. CLUBS  (FR11)
-- ============================================================

CREATE TABLE clubs (
    club_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_name       VARCHAR(120) NOT NULL UNIQUE,
    description     TEXT,
    department_id   INTEGER,
    club_head_id    INTEGER,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_clubs_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id),

    CONSTRAINT fk_clubs_club_head
        FOREIGN KEY (club_head_id) REFERENCES users(user_id)
);

CREATE TRIGGER trg_clubs_updated_at
    BEFORE UPDATE ON clubs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 9. CLUB MEMBERS  (FR11 - "manage organizing team members")
-- ============================================================

CREATE TABLE club_members (
    club_member_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id         INTEGER     NOT NULL,
    user_id         INTEGER     NOT NULL,
    position        VARCHAR(64) NOT NULL DEFAULT 'MEMBER',
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_club_members_club
        FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE CASCADE,

    CONSTRAINT fk_club_members_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT uq_club_members UNIQUE (club_id, user_id)
);


-- ============================================================
-- 10. EVENTS  (FR14 category filtering, FR17 recommendations)
-- booked_seats is a denormalised counter maintained inside the same
-- transaction as event_registrations; chk_events_booked_within_capacity
-- is the hard backstop against overbooking (FR15).
-- ============================================================

CREATE TABLE events (
    event_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- NULL for an official department / college event booked directly by
    -- faculty (FR12 "Direct Faculty Booking"), which has no organising club.
    club_id          INTEGER,
    -- Routes approval (FR12): the organising club's department, or NULL for
    -- a college-level event, which goes to the Principal / HOD.
    department_id    INTEGER,
    created_by       INTEGER      NOT NULL,
    title            VARCHAR(200) NOT NULL,
    description      TEXT,
    category         VARCHAR(32)  NOT NULL,
    event_scope      VARCHAR(16)  NOT NULL DEFAULT 'CLUB',
    event_date       DATE         NOT NULL,
    start_time       TIME         NOT NULL,
    end_time         TIME         NOT NULL,
    status           VARCHAR(24)  NOT NULL DEFAULT 'DRAFT',
    max_seats        INTEGER,
    booked_seats     INTEGER      NOT NULL DEFAULT 0,
    banner_url       TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_events_club
        FOREIGN KEY (club_id) REFERENCES clubs(club_id),

    CONSTRAINT fk_events_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id),

    -- A club event must name its club.
    CONSTRAINT chk_events_club_scope CHECK (event_scope <> 'CLUB' OR club_id IS NOT NULL),

    CONSTRAINT fk_events_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),

    CONSTRAINT chk_events_category CHECK (category IN (
        'TECHNICAL', 'CULTURAL', 'SPORTS', 'WORKSHOP',
        'SEMINAR', 'PLACEMENT', 'SOCIAL', 'OTHER'
    )),

    CONSTRAINT chk_events_scope CHECK (event_scope IN ('CLUB', 'DEPARTMENT', 'COLLEGE')),

    CONSTRAINT chk_events_status CHECK (status IN (
        'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED',
        'REJECTED', 'CANCELLED', 'COMPLETED'
    )),

    CONSTRAINT chk_events_time CHECK (end_time > start_time),
    CONSTRAINT chk_events_max_seats CHECK (max_seats IS NULL OR max_seats > 0),
    CONSTRAINT chk_events_booked_seats CHECK (booked_seats >= 0),

    CONSTRAINT chk_events_booked_within_capacity CHECK (
        max_seats IS NULL OR booked_seats <= max_seats
    )
);

CREATE TRIGGER trg_events_updated_at
    BEFORE UPDATE ON events
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ------------------------------------------------------------
-- 10a. EVENT ELIGIBILITY (FR15) - two junction tables, not one
--
-- events.eligible_departments INTEGER[] and eligible_years SMALLINT[] were
-- each a 1NF violation (a repeating group). They are decomposed here as TWO
-- separate junction tables rather than one combined
-- (event_id, department_id, academic_year) table - see CLAUDE.md's database
-- rules. "Eligible departments" and "eligible years" are independent facts
-- about an event: an event open to IT and CS, for years 2 and 3, means
-- "IT or CS" AND "year 2 or 3" - four combinations, not two rows. Combining
-- them into one table would force choosing a subset of that cross product
-- to store, which is a 4NF violation (a cartesian product masquerading as
-- one fact). Both composite PKs, both empty by default (empty = open to
-- everyone on that dimension, same convention the arrays used).
-- ------------------------------------------------------------

CREATE TABLE event_eligible_departments (
    event_id        INTEGER NOT NULL,
    department_id   INTEGER NOT NULL,

    PRIMARY KEY (event_id, department_id),

    CONSTRAINT fk_event_eligible_departments_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_event_eligible_departments_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id) ON DELETE CASCADE
);

CREATE TABLE event_eligible_years (
    event_id        INTEGER  NOT NULL,
    academic_year   SMALLINT NOT NULL,

    PRIMARY KEY (event_id, academic_year),

    CONSTRAINT fk_event_eligible_years_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT chk_event_eligible_years_range CHECK (academic_year BETWEEN 1 AND 5)
);


-- ============================================================
-- 11. BOOKINGS  (FR7-FR13)
--
-- start_at / end_at are the authoritative venue reservation window and
-- are the ONLY columns the conflict engine reads. They are derived by
-- the application from the event schedule at request time; events keeps
-- event_date/start_time/end_time for display and reporting.
--
-- The EXCLUDE constraint is the last line of defence: even if the
-- application-level SELECT ... FOR UPDATE logic (FR10) were buggy,
-- PostgreSQL itself refuses two overlapping APPROVED bookings on one
-- venue. The configurable setup/teardown buffer (FR9) is applied by the
-- application query, which is why the constraint uses the raw window.
-- ============================================================

CREATE TABLE bookings (
    booking_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id            INTEGER      NOT NULL,
    venue_id            INTEGER      NOT NULL,
    requested_by        INTEGER      NOT NULL,
    approved_by         INTEGER,
    start_at            TIMESTAMPTZ  NOT NULL,
    end_at              TIMESTAMPTZ  NOT NULL,
    extension_minutes   SMALLINT     NOT NULL DEFAULT 0,
    -- Setup/teardown buffer (FR9) in force when the request was made. Frozen
    -- per booking so a later settings change cannot retroactively create
    -- conflicts between already-approved bookings.
    buffer_minutes      SMALLINT     NOT NULL DEFAULT 0,
    -- TRUE when faculty booked directly, skipping the pending step (FR12).
    is_direct           BOOLEAN      NOT NULL DEFAULT FALSE,
    status              VARCHAR(24)  NOT NULL DEFAULT 'PENDING',
    rejection_reason    TEXT,
    -- FR13 "Request Modification": what the approver asked the club to change.
    -- Kept after the club resubmits so the approver can see what they asked for.
    modification_note   TEXT,
    -- How many times the requester has edited and resubmitted this request.
    revision            SMALLINT     NOT NULL DEFAULT 0,
    decided_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bookings_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_bookings_venue
        FOREIGN KEY (venue_id) REFERENCES venues(venue_id),

    CONSTRAINT fk_bookings_requested_by
        FOREIGN KEY (requested_by) REFERENCES users(user_id),

    CONSTRAINT fk_bookings_approved_by
        FOREIGN KEY (approved_by) REFERENCES users(user_id),

    CONSTRAINT chk_bookings_status CHECK (status IN (
        'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'MODIFICATION_REQUESTED'
    )),

    CONSTRAINT chk_bookings_window CHECK (end_at > start_at),

    CONSTRAINT chk_bookings_extension CHECK (
        extension_minutes >= 0 AND extension_minutes <= 15
    ),

    CONSTRAINT chk_bookings_buffer CHECK (buffer_minutes >= 0 AND buffer_minutes <= 120),

    -- FR13: a rejection must carry a recorded reason.
    CONSTRAINT chk_bookings_rejection_reason CHECK (
        status <> 'REJECTED' OR (rejection_reason IS NOT NULL AND length(btrim(rejection_reason)) > 0)
    ),

    -- FR13: sending a request back must say what to change.
    CONSTRAINT chk_bookings_modification_note CHECK (
        status <> 'MODIFICATION_REQUESTED' OR (modification_note IS NOT NULL AND length(btrim(modification_note)) > 0)
    ),

    CONSTRAINT chk_bookings_revision CHECK (revision >= 0),

    -- Any decided booking records who decided it and when.
    CONSTRAINT chk_bookings_decision_audit CHECK (
        status IN ('PENDING', 'CANCELLED')
        OR (approved_by IS NOT NULL AND decided_at IS NOT NULL)
    ),

    -- FR10: zero duplicate venue bookings, enforced by the database.
    CONSTRAINT excl_bookings_no_overlap
        EXCLUDE USING gist (
            venue_id WITH =,
            tstzrange(start_at, end_at, '[)') WITH &&
        ) WHERE (status = 'APPROVED')
);

CREATE TRIGGER trg_bookings_updated_at
    BEFORE UPDATE ON bookings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 12. EVENT REGISTRATIONS / RSVP  (FR15, FR16)
-- Distinct from attendance: this is the seat reservation, attendance is
-- what happened on the day.
-- ============================================================

CREATE TABLE event_registrations (
    registration_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         INTEGER     NOT NULL,
    student_id       INTEGER     NOT NULL,
    status           VARCHAR(16) NOT NULL DEFAULT 'RESERVED',
    seats            SMALLINT    NOT NULL DEFAULT 1,
    registered_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at     TIMESTAMPTZ,

    CONSTRAINT fk_event_registrations_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_event_registrations_student
        FOREIGN KEY (student_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT uq_event_registrations UNIQUE (event_id, student_id),

    CONSTRAINT chk_event_registrations_status CHECK (
        status IN ('RESERVED', 'CANCELLED', 'WAITLISTED')
    ),

    CONSTRAINT chk_event_registrations_seats CHECK (seats > 0),

    CONSTRAINT chk_event_registrations_cancel CHECK (
        (status = 'CANCELLED') = (cancelled_at IS NOT NULL)
    )
);

-- FR15 seat safety already has an application-level guard: register() in
-- event.service.js takes SELECT ... FOR UPDATE on the events row before
-- deciding whether a seat is free, and chk_events_booked_within_capacity
-- backstops the stored booked_seats counter that guard maintains. This
-- trigger is a second, independent guard at the row level being written -
-- it recomputes live demand straight from event_registrations rather than
-- trusting the booked_seats counter, so it still catches an overbook even
-- if that counter were ever wrong (a raw psql INSERT bypassing the app
-- entirely, for instance). Both guards agree in normal operation; this one
-- runs inside the same transaction and the same already-locked events row,
-- so it adds no new lock ordering to reason about.
CREATE OR REPLACE FUNCTION enforce_event_registration_capacity()
RETURNS TRIGGER AS $$
DECLARE
    v_max_seats INTEGER;
    v_reserved  INTEGER;
BEGIN
    IF NEW.status <> 'RESERVED' THEN
        RETURN NEW;
    END IF;

    SELECT max_seats INTO v_max_seats FROM events WHERE event_id = NEW.event_id FOR UPDATE;
    IF v_max_seats IS NULL THEN
        RETURN NEW;  -- NULL max_seats means unlimited (FR15 convention)
    END IF;

    SELECT COALESCE(SUM(seats), 0) INTO v_reserved
      FROM event_registrations
     WHERE event_id = NEW.event_id AND status = 'RESERVED'
       AND registration_id <> NEW.registration_id;

    IF v_reserved + NEW.seats > v_max_seats THEN
        RAISE EXCEPTION 'event % capacity exceeded: % reserved + % new > % max',
            NEW.event_id, v_reserved, NEW.seats, v_max_seats
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_event_registrations_capacity
    BEFORE INSERT OR UPDATE ON event_registrations
    FOR EACH ROW EXECUTE FUNCTION enforce_event_registration_capacity();


-- ============================================================
-- 13. ATTENDANCE
-- ============================================================

CREATE TABLE attendance (
    attendance_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INTEGER     NOT NULL,
    student_id      INTEGER     NOT NULL,
    status          VARCHAR(16) NOT NULL,
    marked_by       INTEGER,
    marked_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_attendance_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_attendance_student
        FOREIGN KEY (student_id) REFERENCES users(user_id),

    CONSTRAINT fk_attendance_marked_by
        FOREIGN KEY (marked_by) REFERENCES users(user_id),

    CONSTRAINT uq_attendance_event_student UNIQUE (event_id, student_id),

    CONSTRAINT chk_attendance_status CHECK (status IN ('PRESENT', 'ABSENT', 'EXCUSED'))
);


-- ============================================================
-- 14. CERTIFICATES
-- NOTE: certificates and event_materials are implemented here but are
-- not described in the SRS. Either add them to SRS section 10 or drop
-- these two tables before the final review.
-- ============================================================

CREATE TABLE certificates (
    certificate_uuid    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id            INTEGER     NOT NULL,
    student_id          INTEGER     NOT NULL,
    certificate_type    VARCHAR(32) NOT NULL,
    issued_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_certificates_event
        FOREIGN KEY (event_id) REFERENCES events(event_id),

    CONSTRAINT fk_certificates_student
        FOREIGN KEY (student_id) REFERENCES users(user_id),

    CONSTRAINT uq_certificate_event_student_type
        UNIQUE (event_id, student_id, certificate_type),

    CONSTRAINT chk_certificates_type CHECK (
        certificate_type IN ('PARTICIPATION', 'WINNER', 'ORGANIZER', 'VOLUNTEER')
    )
);


-- ============================================================
-- 15. EVENT MATERIALS
-- ============================================================

CREATE TABLE event_materials (
    material_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INTEGER      NOT NULL,
    title           VARCHAR(200) NOT NULL,
    file_url        TEXT         NOT NULL,
    file_type       VARCHAR(32),
    uploaded_by     INTEGER,
    uploaded_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_event_materials_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_event_materials_uploaded_by
        FOREIGN KEY (uploaded_by) REFERENCES users(user_id)
);


-- ============================================================
-- 16. NOTIFICATIONS  (FR19)
-- ============================================================

CREATE TABLE notifications (
    notification_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            INTEGER      NOT NULL,
    event_id           INTEGER,
    booking_id         INTEGER,
    category           VARCHAR(32)  NOT NULL DEFAULT 'GENERAL',
    title              VARCHAR(200) NOT NULL,
    message            TEXT         NOT NULL,
    is_read            BOOLEAN      NOT NULL DEFAULT FALSE,
    read_at            TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT fk_notifications_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT fk_notifications_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,

    CONSTRAINT chk_notifications_category CHECK (category IN (
        'GENERAL', 'EVENT_PUBLISHED', 'EVENT_REMINDER', 'EVENT_CANCELLED',
        'BOOKING_APPROVED', 'BOOKING_REJECTED', 'REGISTRATION_CONFIRMED', 'ANNOUNCEMENT',
        'BOOKING_REQUESTED', 'BOOKING_CHANGES_REQUESTED', 'BOOKING_CANCELLED', 'CLUB_MEMBERSHIP'
    ))
);


-- ============================================================
-- 17. EVENT REMINDERS  (FR19 - the 2-day / 2-hour scheduled workers)
-- The UNIQUE constraint is what makes the worker idempotent: a restart
-- or an overlapping tick cannot send the same reminder twice.
-- ============================================================

CREATE TABLE event_reminders (
    reminder_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INTEGER     NOT NULL,
    reminder_type   VARCHAR(16) NOT NULL,
    scheduled_for   TIMESTAMPTZ NOT NULL,
    dispatched_at   TIMESTAMPTZ,
    recipient_count INTEGER,

    CONSTRAINT fk_event_reminders_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,

    CONSTRAINT uq_event_reminders UNIQUE (event_id, reminder_type),

    CONSTRAINT chk_event_reminders_type CHECK (reminder_type IN ('T_MINUS_2D', 'T_MINUS_2H'))
);


-- ============================================================
-- 18. ADMIN LOGS  (FR20 - immutable audit trail)
-- ============================================================

CREATE TABLE admin_logs (
    log_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id        INTEGER      NOT NULL,
    booking_id      INTEGER,
    action          VARCHAR(64)  NOT NULL,
    target_type     VARCHAR(32),
    target_id       INTEGER,
    details         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    ip_address      INET,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_admin_logs_admin
        FOREIGN KEY (admin_id) REFERENCES users(user_id),

    CONSTRAINT fk_admin_logs_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE SET NULL
);

-- FR20 says the audit trail is immutable. Enforce it in the database so
-- that no application bug - and no ad-hoc psql session - can rewrite history.
CREATE OR REPLACE FUNCTION reject_admin_log_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'admin_logs is append-only (attempted %)', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_admin_logs_immutable
    BEFORE UPDATE OR DELETE ON admin_logs
    FOR EACH ROW EXECUTE FUNCTION reject_admin_log_mutation();


-- ============================================================
-- VIEWS  (DBMS Unit 4 - FR21 reporting, in plain SQL)
--
-- Written with ordinary GROUP BY / HAVING / CASE and plain JOINs - not the
-- FILTER (WHERE ...) clause or window functions PostgreSQL also offers,
-- which the syllabus does not teach at this level (see CLAUDE.md's database
-- rules). Each aggregate below is lifetime-to-date: a view is a stored
-- SELECT with no parameters, so it cannot itself take a runtime date range.
-- The FR21 report API (reports/metrics.service.js) still needs a
-- caller-chosen period, so it keeps its own parameterized query rather than
-- selecting from these views - but it is written in the same plain
-- CASE/GROUP BY form these views use, not FILTER/window syntax either.
-- These views are queryable directly (`SELECT * FROM v_venue_utilisation;`)
-- for a faculty demo of the lifetime totals.
-- ============================================================

CREATE VIEW v_venue_utilisation AS
SELECT
    v.venue_id,
    v.venue_name,
    v.building,
    v.capacity,
    count(CASE WHEN b.status = 'APPROVED' THEN 1 END)::int  AS approved_bookings,
    count(CASE WHEN b.status = 'CANCELLED' THEN 1 END)::int AS cancelled_bookings,
    COALESCE(SUM(CASE WHEN b.status = 'APPROVED'
                       THEN EXTRACT(EPOCH FROM (b.end_at - b.start_at)) / 3600
                  END), 0) AS approved_hours
FROM venues v
LEFT JOIN bookings b ON b.venue_id = v.venue_id
WHERE v.is_active
GROUP BY v.venue_id, v.venue_name, v.building, v.capacity;

CREATE VIEW v_club_activity AS
SELECT
    c.club_id,
    c.club_name,
    d.dept_code,
    count(DISTINCT e.event_id)::int AS total_events,
    count(DISTINCT CASE WHEN e.status IN ('PUBLISHED', 'COMPLETED') THEN e.event_id END)::int AS published_events,
    count(DISTINCT CASE WHEN e.status = 'CANCELLED' THEN e.event_id END)::int AS cancelled_events,
    count(CASE WHEN r.status <> 'CANCELLED' THEN r.registration_id END)::int AS total_registrations,
    COALESCE(SUM(CASE WHEN r.status = 'RESERVED' THEN r.seats END), 0)::int AS seats_filled
FROM clubs c
LEFT JOIN departments d ON d.department_id = c.department_id
LEFT JOIN events e ON e.club_id = c.club_id
LEFT JOIN event_registrations r ON r.event_id = e.event_id
WHERE c.is_active
GROUP BY c.club_id, c.club_name, d.dept_code
-- A club that has never run an event adds nothing to a "most active club"
-- report; HAVING drops it after the aggregation, which a WHERE on e.event_id
-- could not (that column does not exist until the GROUP BY has run).
HAVING count(DISTINCT e.event_id) > 0;

CREATE VIEW v_event_attendance AS
SELECT
    e.event_id,
    e.title,
    e.event_date,
    e.category,
    COALESCE(c.club_name, d.dept_name, 'College event') AS organiser,
    count(CASE WHEN r.status = 'RESERVED' THEN r.registration_id END)::int AS registered,
    count(CASE WHEN a.status = 'PRESENT' THEN a.attendance_id END)::int AS present,
    count(CASE WHEN a.status = 'ABSENT' THEN a.attendance_id END)::int AS absent,
    count(CASE WHEN a.status = 'EXCUSED' THEN a.attendance_id END)::int AS excused
FROM events e
LEFT JOIN clubs c ON c.club_id = e.club_id
LEFT JOIN departments d ON d.department_id = e.department_id
LEFT JOIN event_registrations r ON r.event_id = e.event_id
LEFT JOIN attendance a ON a.event_id = e.event_id
WHERE e.status IN ('PUBLISHED', 'COMPLETED')
GROUP BY e.event_id, e.title, e.event_date, e.category, c.club_name, d.dept_name;

-- A simple, single-table, no-aggregation view is updatable in PostgreSQL:
-- a change through the view writes straight to the underlying table. Useful
-- for a coordinator-facing screen that should only ever see active venues,
-- without duplicating the venues table's columns or write logic.
CREATE VIEW v_active_venues AS
SELECT venue_id, venue_name, building, floor, venue_type, capacity, department_id
  FROM venues
 WHERE is_active;


-- ============================================================
-- STORED FUNCTIONS  (DBMS Unit 2 - PL/pgSQL routines and an explicit cursor)
-- ============================================================

-- A standalone PL/pgSQL equivalent of the FR15 registration transaction:
-- lock the event, check it is open, insert, bump the seat counter.
-- trg_event_registrations_capacity above still rejects an overbooking
-- insert before this function ever sees success.
--
-- Deliberately NOT the live API's registration path. event.service.js's
-- register() additionally handles waitlisting, eligibility rules and
-- notifications - real business policy that belongs in the application
-- layer, not hard-coded into a database routine. This function demonstrates
-- the syllabus construct on the project's own schema and is directly
-- callable (`SELECT register_for_event(...)`) for that purpose.
-- p_seats is INTEGER, not the SMALLINT event_registrations.seats stores:
-- Postgres's function-overload resolution only widens (smallint -> integer)
-- implicitly, it never narrows, so a plain integer literal or a JS number
-- passed as int4 (the common case from node-postgres) would otherwise fail
-- to resolve against a smallint parameter. The INSERT below narrows it back
-- on assignment into the column, which is always allowed.
CREATE OR REPLACE FUNCTION register_for_event(p_event_id INTEGER, p_student_id INTEGER, p_seats INTEGER DEFAULT 1)
RETURNS INTEGER AS $$
DECLARE
    v_status           VARCHAR(24);
    v_registration_id  INTEGER;
BEGIN
    SELECT status INTO v_status FROM events WHERE event_id = p_event_id FOR UPDATE;
    IF v_status IS NULL THEN
        RAISE EXCEPTION 'event % does not exist', p_event_id USING ERRCODE = 'no_data_found';
    END IF;
    IF v_status <> 'PUBLISHED' THEN
        RAISE EXCEPTION 'event % is not open for registration (status %)', p_event_id, v_status
            USING ERRCODE = 'check_violation';
    END IF;

    INSERT INTO event_registrations (event_id, student_id, seats)
    VALUES (p_event_id, p_student_id, p_seats)
    RETURNING registration_id INTO v_registration_id;

    UPDATE events SET booked_seats = booked_seats + p_seats WHERE event_id = p_event_id;

    RETURN v_registration_id;
END;
$$ LANGUAGE plpgsql;

-- Nothing currently ever marks an event COMPLETED - a real gap this closes.
-- Uses an explicit cursor rather than a single UPDATE ... WHERE so each
-- event is locked and closed one row at a time, matching the row-by-row
-- processing the syllabus's cursor unit teaches (a single set-based UPDATE
-- would be shorter, but would not be a cursor).
CREATE OR REPLACE FUNCTION close_past_events()
RETURNS INTEGER AS $$
DECLARE
    v_cur CURSOR FOR
        SELECT e.event_id
          FROM events e
          JOIN bookings b ON b.event_id = e.event_id AND b.status = 'APPROVED'
         WHERE e.status = 'PUBLISHED' AND b.end_at < now()
         FOR UPDATE OF e;
    v_event_id INTEGER;
    v_count    INTEGER := 0;
BEGIN
    OPEN v_cur;
    LOOP
        FETCH v_cur INTO v_event_id;
        EXIT WHEN NOT FOUND;
        UPDATE events SET status = 'COMPLETED' WHERE event_id = v_event_id;
        v_count := v_count + 1;
    END LOOP;
    CLOSE v_cur;
    RETURN v_count;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- INDEXES
-- Only indexes backing a query the application actually issues.
-- ============================================================

CREATE INDEX idx_users_role_id             ON users(role_id);
CREATE INDEX idx_users_department_id       ON users(department_id);

CREATE INDEX idx_refresh_tokens_user_id    ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);
CREATE INDEX idx_refresh_tokens_family_id  ON refresh_tokens(family_id);

-- Backs "latest live code for this email" and the resend-rate check.
CREATE INDEX idx_otps_email_purpose        ON otps(email, purpose, created_at DESC);

CREATE INDEX idx_venues_building_floor     ON venues(building, floor);
CREATE INDEX idx_venues_department_id      ON venues(department_id);
CREATE INDEX idx_venues_capacity           ON venues(capacity);
-- The PK (venue_id, equipment_id) already covers "this venue's equipment";
-- this covers the reverse direction, "which venues have X" (the equipment
-- filter in listVenues joins from equipment_id outward).
CREATE INDEX idx_venue_equipment_equipment_id ON venue_equipment(equipment_id);

CREATE INDEX idx_clubs_club_head_id        ON clubs(club_head_id);
CREATE INDEX idx_clubs_department_id       ON clubs(department_id);

CREATE INDEX idx_club_members_user_id      ON club_members(user_id);

CREATE INDEX idx_events_club_id            ON events(club_id);
CREATE INDEX idx_events_department_id      ON events(department_id);
CREATE INDEX idx_events_created_by         ON events(created_by);
CREATE INDEX idx_events_event_date         ON events(event_date);
CREATE INDEX idx_events_status             ON events(status);
CREATE INDEX idx_events_category           ON events(category);
-- Backs the student discovery feed (FR14): published events, soonest first.
CREATE INDEX idx_events_feed               ON events(event_date, start_time)
    WHERE status = 'PUBLISHED';

-- The PKs already cover "this event's eligible X"; these cover the reverse
-- direction, "events eligible for department/year Y" (dashboard.service.js).
CREATE INDEX idx_event_eligible_departments_department_id ON event_eligible_departments(department_id);
CREATE INDEX idx_event_eligible_years_academic_year        ON event_eligible_years(academic_year);

CREATE INDEX idx_bookings_event_id         ON bookings(event_id);
CREATE INDEX idx_bookings_requested_by     ON bookings(requested_by);
CREATE INDEX idx_bookings_approved_by      ON bookings(approved_by);
CREATE INDEX idx_bookings_status           ON bookings(status);
-- Backs the conflict-detection scan (FR8) and the calendar view.
CREATE INDEX idx_bookings_venue_window     ON bookings(venue_id, start_at, end_at);
-- Backs the coordinator approval inbox (FR13).
CREATE INDEX idx_bookings_pending_inbox    ON bookings(venue_id, start_at)
    WHERE status = 'PENDING';
-- One event holds at most one live venue booking (SRS 10.3: one event, one booking).
CREATE UNIQUE INDEX uq_bookings_live_per_event ON bookings(event_id)
    WHERE status IN ('PENDING', 'APPROVED', 'MODIFICATION_REQUESTED');

CREATE INDEX idx_event_registrations_event_id   ON event_registrations(event_id);
CREATE INDEX idx_event_registrations_student_id ON event_registrations(student_id);

CREATE INDEX idx_attendance_event_id       ON attendance(event_id);
CREATE INDEX idx_attendance_student_id     ON attendance(student_id);

CREATE INDEX idx_certificates_event_id     ON certificates(event_id);
CREATE INDEX idx_certificates_student_id   ON certificates(student_id);

CREATE INDEX idx_event_materials_event_id  ON event_materials(event_id);

CREATE INDEX idx_notifications_event_id    ON notifications(event_id);
-- Backs the notification bell: this user's unread items, newest first.
CREATE INDEX idx_notifications_user_unread ON notifications(user_id, created_at DESC)
    WHERE is_read = FALSE;

-- Backs the reminder worker's "what is due now" sweep.
CREATE INDEX idx_event_reminders_due       ON event_reminders(scheduled_for)
    WHERE dispatched_at IS NULL;

CREATE INDEX idx_admin_logs_admin_id       ON admin_logs(admin_id);
CREATE INDEX idx_admin_logs_booking_id     ON admin_logs(booking_id);
CREATE INDEX idx_admin_logs_created_at     ON admin_logs(created_at DESC);
