'use strict';

/**
 * PDF rendering for the FR21 exports.
 *
 * Streamed straight to the response rather than buffered: a report is the
 * one place in CampusOS where the payload has no natural size limit, and
 * holding a whole document in memory to send it is the easy way to turn a
 * big report into an outage.
 *
 * The layout is deliberately plain - title, period, a totals line, a table
 * that repeats its header on every page, and a footer saying where it came
 * from and when. A report that gets printed and signed needs to be legible
 * in black and white, not decorated.
 */

const PDFDocument = require('pdfkit');

const PAGE_MARGIN = 40;
const ROW_HEIGHT = 18;
const HEADER_HEIGHT = 22;
const FONT = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';

/** Fits the spec's relative widths to the page, so nothing overflows. */
function layoutColumns(columns, available) {
  const declared = columns.reduce((sum, c) => sum + (c.width || 100), 0);
  const scale = available / declared;
  return columns.map((column) => ({ ...column, drawWidth: (column.width || 100) * scale }));
}

function drawHeaderRow(doc, columns, y) {
  doc.font(FONT_BOLD).fontSize(9).fillColor('#18181b');
  let x = PAGE_MARGIN;
  columns.forEach((column) => {
    doc.text(column.label, x + 4, y + 6, { width: column.drawWidth - 8, align: column.align || 'left', lineBreak: false });
    x += column.drawWidth;
  });
  doc.moveTo(PAGE_MARGIN, y + HEADER_HEIGHT - 2)
    .lineTo(doc.page.width - PAGE_MARGIN, y + HEADER_HEIGHT - 2)
    .strokeColor('#a1a1aa').lineWidth(0.8).stroke();
  return y + HEADER_HEIGHT;
}

function drawRow(doc, columns, row, y, striped) {
  if (striped) {
    doc.rect(PAGE_MARGIN, y, doc.page.width - PAGE_MARGIN * 2, ROW_HEIGHT).fillColor('#f4f4f5').fill();
  }
  doc.font(FONT).fontSize(9).fillColor('#27272a');
  let x = PAGE_MARGIN;
  columns.forEach((column) => {
    const value = row[column.key];
    doc.text(value === null || value === undefined ? '' : String(value), x + 4, y + 5, {
      width: column.drawWidth - 8,
      align: column.align || 'left',
      lineBreak: false,
      ellipsis: true,
    });
    x += column.drawWidth;
  });
  return y + ROW_HEIGHT;
}

/** "Bookings 42 · Hours 118.5 · Venues 13" - the totals, whatever they are. */
function totalsLine(totals) {
  return Object.entries(totals)
    .map(([key, value]) => `${key.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase())}: ${value}`)
    .join('   ·   ');
}

/**
 * Writes the report into `stream` (normally the HTTP response).
 *
 * @param {{ spec: object, rows: object[], totals: object, period: object,
 *           generatedBy: string, generatedAt: string }} report
 * @param {NodeJS.WritableStream} stream
 * @returns {NodeJS.WritableStream} the same stream, for chaining
 */
function render({ spec, rows, totals, period, generatedBy, generatedAt }, stream) {
  const doc = new PDFDocument({
    size: 'A4',
    layout: 'landscape',
    margin: PAGE_MARGIN,
    info: { Title: `CampusOS - ${spec.title}`, Author: 'CampusOS' },
  });
  doc.pipe(stream);

  doc.font(FONT_BOLD).fontSize(16).fillColor('#18181b').text(spec.title);
  doc.font(FONT).fontSize(9).fillColor('#52525b')
    .text(`${spec.description}   ·   ${period.from} to ${period.to}`);
  if (totals && Object.keys(totals).length) {
    doc.moveDown(0.4).fontSize(9).fillColor('#3f3f46').text(totalsLine(totals));
  }
  doc.moveDown(0.8);

  const available = doc.page.width - PAGE_MARGIN * 2;
  const columns = layoutColumns(spec.columns, available);
  const bottom = doc.page.height - PAGE_MARGIN - 24;
  let y = drawHeaderRow(doc, columns, doc.y);

  if (rows.length === 0) {
    doc.font(FONT).fontSize(10).fillColor('#71717a').text('Nothing recorded in this period.', PAGE_MARGIN, y + 10);
  }

  rows.forEach((row, index) => {
    if (y + ROW_HEIGHT > bottom) {
      doc.addPage();
      y = drawHeaderRow(doc, columns, PAGE_MARGIN);
    }
    y = drawRow(doc, columns, row, y, index % 2 === 1);
  });

  // The footer is what makes a printed copy accountable: who ran it, when.
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    doc.font(FONT).fontSize(8).fillColor('#71717a').text(
      `CampusOS · ${spec.title} · generated by ${generatedBy} on ${generatedAt} · page ${i - range.start + 1} of ${range.count}`,
      PAGE_MARGIN,
      doc.page.height - PAGE_MARGIN + 4,
      { width: available, align: 'center', lineBreak: false },
    );
  }

  doc.end();
  return stream;
}

module.exports = { render, layoutColumns, totalsLine, PAGE_MARGIN, ROW_HEIGHT };
